### ISSUE TITLE
pgAdmin total failure on course VM

### ISSUE THREAD

**Issue by Fail-staff** [gabrielmartell/COMP3005-Project-Template#9] opened 2024-04-04 18:06 UTC
Hey just posting this here, having some issues running pdadmin4 on the VM.

It was working fine yesterday but now I get this error when I run the pgadmin4
![image](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/93552944/8b0c0075-3ea4-41c4-88ad-5dedfcb603a1)

When a check my file manager using df -h it tells me that 0 bytes are free out of 9.8 GB of space (using 9.3). This makes no sense and was not the case just a few short hours ago.

I don't understand why pgadmin just randomly crapped out on me, but now I cant run anything I cant even run the autograder or anything at all on my system, all connections are being rejected.

![image (1)](https://github.com/gabrielmartell/COMP3005-Project-Template/assets/93552944/776afb15-1851-4603-8eed-1c2c4bd48cad)

do you know any way to fix this? I can't find anything online, I'm thinking it is something to do with temp files being permanently stored by mistake? I dont know anything about linux so I really am not sure how to fix this

thanks,

Ben Seguin

**Comment by gabrielmartell** [comment] 2024-04-04 18:40
Hi @Fail-staff,

I unfortunately have never encountered this error before, but I'll try my best to help you out.

From your first snippet, 
The errors **ReadExactly: ...** and **write: No space left on the device**, from my understanding, is pgAdmin4 failing from launching as there isn't enough storage to read and write data while running. Therefore, you must have installed something, or currently running something, that takes up too much space. You can view this [article,](https://linuxconfig.org/resolving-the-no-space-left-on-device-error-on-linux) as this might be the answer to your issue (assuming you didn't read this yet). 

From your second snippet, I am assuming that the cause of this problem arises from the first issue, that is, there isn't enough space to run or do anything as too much space is now being used. 

If that isn't the case, I am _guessing_ that your project_database.py and whatever your listed port and host name is wrong, maybe an accidental key click. Otherwise maybe you can try something from [this stackoverflow link](https://stackoverflow.com/questions/32439167/psql-could-not-connect-to-server-connection-refused-error-when-connecting-to) with a similar issue.

I'm really sorry this happened and I'm sorry that I can't be much help,
Please let me know if you need further assistance,
Gabe

**Comment by gabrielmartell** [comment] 2024-04-08 16:05
Hi @Fail-staff 

Hopefully all is well, I'm assuming by your lack of follow-up that all was solved.
but if it wasnt, please shoot another issue if you haven't figured this out yet.

Thanks,
Gabe

**Closed by gabrielmartell** 2024-04-08 16:05 UTC
